name: VideoToMinecraft
author: birthdates
version: 1.4.0
main: com.birthdates.videotominecraft.VideoToMinecraft
description: A plugin to read video files and allow you to watch it in minecraft using ffmpeg
api-version: 1.13
commands:
  watch:
  watchmovie:
  stopwatching:

permissions:
  videotominecraft.watch:
    description: "Used for /watch"
  videotominecraft.watchmovie:
    description: "Used for /watchmovie"